name: Cryptol typecheck
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/galoisinc/cryptol:nightly
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Cryptol Version
      run: cryptol --version

    - name: Checkout Cryptol Specs
      uses: actions/checkout@v3
      with:
          repository: GaloisInc/cryptol-specs
          path: cryptol-specs/

    - name: Setup Enviornment
      run: echo "CRYPTOLPATH=.:cryptol-specs" >> $GITHUB_ENV

    - name: Test
      run: ls && echo $CRYPTOLPATH

    - name: Check Cryptol Files
      run: bash scripts/load_all_cry_files.sh
